### ISSUE TITLE
Projection test fails for (n, )

### ISSUE THREAD

**Issue by krusejake** [cs540-testers/hw5-tester#2]
Got the following fail/error message:

Traceback (most recent call last):
  File "test.py", line 120, in test_shape
    self.assertEqual(np.shape(projected), (784, 1))
AssertionError: Tuples differ: (784,) != (784, 1)

Second tuple contains 1 additional elements.
First extra element 1:
1

- (784,)
+ (784, 1)
?      ++
Snapshot:
![image](https://user-images.githubusercontent.com/47227749/97027432-55f21f80-1520-11eb-8136-bffc80a8efd4.png)

Per https://stackoverflow.com/questions/39549331/reshape-numpy-n-vector-to-n-1-vector and similar, looks like (784, ) is equivalent to (784, 1).

**Comment by StephenJasina** [comment]
Reading the post you linked, it is pointed out that a shape of `(784, )` is actually different than `(784, 1)` (the former being a row vector and the latter being a column vector). As the spec states "project each image into your m-dimensional space and **return** the new representation as a d x 1 NumPy array," it is implied we should return a column vector.

**Comment by StephenJasina** [comment]
After a thorough perusal of Piazza, it seems the instructors do want an output of shape `(784,)`. I will work on a fix now

**Comment by StephenJasina** [comment]
Pushed now
